### ISSUE TITLE
Document the query performance implications of area vs. bbox for complex boundary polygons

### ISSUE THREAD

**Issue by mikaelhg** [fmidev/smartmet-plugin-timeseries#77]
In the "Areas" chapter of the "Using" document, please make obvious the performance implications of using the `area` or `areas` parameter with complex polygons, such as `Finland`, vs. using a `bbox` parameter of value `20.6455928891,59.846373196,31.5160921567,70.1641930203` or simplified `20.65,59.85,31.52,70.16`.

For some queries, the PostGIS intersection calculation takes significantly longer than fetching the actual data, and aggregating it. Not to mention, `area=Finland` doesn't even capture all observations in Finland, perhaps because the polygon has to be simplified because of performance reasons, and this accidentally cuts off some border posts etc.

An example, where we fetch the fmisid to name mappings:

Fast:   
https://opendata.fmi.fi/timeseries?format=json&precision=double&groupareas=0&producer=airquality_urban&param=fmisid,region,iso2,name,latitude,longitude&starttime=-1d&timestep=1d&bbox=20.6455928891,59.846373196,31.5160921567,70.1641930203

Slow:   
https://opendata.fmi.fi/timeseries?format=json&precision=double&groupareas=0&producer=airquality_urban&param=fmisid,region,iso2,name,latitude,longitude&starttime=-1d&timestep=1d&area=Finland

**Comment by mheiskan** [comment]
The code seems to generate a WKT string for the database driver for a SQL ST_Contains query. This makes no sense, since the result of the query result is constant if we ignore time restrictions (old stations), which can be be applied in a post filter step very quickly. The code can be rewritten quite easily to cache such intermediate results, but due to the vacation season and the queue of open tickects (private to FMI) it may not happen until autumn. The first to apply such a search after a server restart will still suffer a time penalty though.

**Comment by mheiskan** [comment]
The polygon "Finland" is not of the highest possible accuracy, and may not even cover sea areas very well, as the polygon probably covers only land areas. An area which includes all national sea areas probably exists in the FMI database, but I'll have to examine it in more detail after the vacation season.

**Comment by mheiskan** [comment]
However, for your purposes you might want to replace bbox/area settings with keyword=air_quality_urban, which lists all air quality stations external to FMI. Unfortunately the list of available keywords is not yet well documented.

**Comment by mikaelhg** [comment]
Thanks for the tip about the `keyword`, I'll have to look at that. Certainly returned quite a number of stations which the bounding box query didn't return. I'm glad that we had an intersection where a hobbyist has time for this during vacation, and the professional hasn't quite yet had the time to catch their vacation flight.
