### ISSUE TITLE
Minor security concern

### ISSUE THREAD

**Issue by mikaelhg** [fmidev/smartmet-plugin-timeseries#80]
I noticed a security issue that might be worth fixing, but since you can't submit non-public issues here, I'll email the ticket to beta@fmi.fi. If it gets lost, you can contact me.

**Comment by mheiskan** [comment]
You can email me directly at mika dot heiskanen at fmi dot fi. The developers are unlikely to be at beta@fmi.fi mailing list, at least I did not get any email.

**Comment by mikaelhg** [comment]
One explanation for that might be that I hadn't actually clicked on the send button yet, but I changed the address to yours instead. Closing this issue, I assume you'll track it internally.
